// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1742537421);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1742537421);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1742537421);
user_pref("app.update.lastUpdateTime.region-update-timer", 1742537421);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1742537421);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1742537421);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1742537453);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1742537421);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{6fc8c3af-c716-4d2e-96f3-715f9651439f}");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1742537391);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 142);
user_pref("browser.newtabpage.activity-stream.impressionId", "{422c73a9-1142-4796-8b4f-60f39f8c9cd9}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1742537392);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1742537412246");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1742539234246");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1742537411429");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1742559011429");
user_pref("browser.search.region", "CN");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20240214103141");
user_pref("browser.startup.homepage_override.mstone", "123.0");
user_pref("browser.startup.lastColdStartupCheck", 1742537393);
user_pref("browser.topsites.contile.lastFetch", 1742537696);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1742537400989");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "123.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "CN");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "6b0c80c7ddc74a96b0f9ffa6e05e8b0c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1742537423);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-US@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20240214103141");
user_pref("extensions.lastAppVersion", "123.0");
user_pref("extensions.lastPlatformVersion", "123.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"3aae2676-7748-4b03-a00a-cdbad1989896\",\"pictureinpicture@mozilla.org\":\"38946bfd-b8af-46b1-a27b-cc8bff3e6232\",\"screenshots@mozilla.org\":\"471d739b-0e18-4acc-b47b-f399bfa710a4\",\"webcompat-reporter@mozilla.org\":\"d4f52bd1-61d3-4d59-8e78-e0a5e7f3d62a\",\"webcompat@mozilla.org\":\"c70bdcbe-c374-4905-8a39-843f3f1d5d4e\",\"default-theme@mozilla.org\":\"4c59a125-2e1e-4f1f-85c6-518ebca4cf71\",\"addons-search-detection@mozilla.com\":\"066bde64-546b-4a8b-b009-fee973d79aab\",\"google@search.mozilla.org\":\"f1d30bab-2d31-4c11-a2af-f92aa744646d\",\"wikipedia@search.mozilla.org\":\"9b2a29f9-5c5d-4c47-85e1-68c11ffa56d2\",\"bing@search.mozilla.org\":\"e7aed8f2-2a07-45ee-81b7-83629f05d14a\",\"ddg@search.mozilla.org\":\"98f3add8-6edf-44e8-9766-115d752bd822\",\"amazondotcn@search.mozilla.org\":\"f002dc05-cbec-4af9-8909-981ec91457eb\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.hashValue", "94531e267314de661b2205c606283fb066d781e5c11027578f2a3c3aa353437c2289544074a28101b6b6f0179f0fe6bd890a0ae2bb6e1cf9053650472576366c");
user_pref("media.gmp-gmpopenh264.lastDownload", 1742537427);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1742537426);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1742537427);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.2");
user_pref("media.gmp-manager.buildID", "20240214103141");
user_pref("media.gmp-manager.lastCheck", 1742537560);
user_pref("media.gmp-manager.lastEmptyCheck", 1742537560);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "01c6b6e4-475d-44bd-aeac-918c26b52f08");
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_update_seconds", 1742537560);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1742537560);
user_pref("services.settings.main.devtools-devices.last_check", 1742537560);
user_pref("services.settings.main.hijack-blocklists.last_check", 1742537560);
user_pref("services.settings.main.language-dictionaries.last_check", 1742537560);
user_pref("services.settings.main.nimbus-desktop-experiments.last_check", 1742537421);
user_pref("services.settings.main.password-recipes.last_check", 1742537560);
user_pref("services.settings.main.sites-classification.last_check", 1742537560);
user_pref("services.settings.main.translations-identification-models.last_check", 1742537560);
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1742537388);
user_pref("toolkit.telemetry.cachedClientID", "bd3232ca-c4b9-49b3-8ddc-eaddc6ec86a5");
user_pref("toolkit.telemetry.previousBuildID", "20240214103141");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
